[package]
name = "ekko"
version = "0.2.0"
authors = ["André Kristiansen"]
description = "Ekko is a simple utility for sending echo requests, giving you (mostly) everything you need."
repository = "https://github.com/dev-bio/ekko"
homepage = "https://github.com/dev-bio/ekko"
readme = "README.md"
license = "MIT"
edition = "2018"

keywords = [
    "icmpv6",
    "icmpv4",
    "icmp",
    "echo",
    "ping",
]

exclude = [
    ".gitattributes",
    ".gitignore",
    
    ".github/**", 
    ".cargo/**", 
]

[dependencies]
thiserror = "1.0.20"
byteorder = "1.3.4"
socket2 = "0.3.15"
rand = "0.8.0"
