[package]
name = "ekko"
version = "0.1.1"
authors = ["André Kristiansen"]
description = "Ekko is a simple utility for sending echo requests, giving you (mostly) everything you need."
repository = "https://github.com/dev-bio/ekko"
homepage = "https://github.com/dev-bio/ekko"
readme = "README.md"
license = "MIT"
edition = "2018"

exclude = [
    ".gitattributes",
    ".gitignore",
    
    ".github/**", 
    ".cargo/**", 
]

[dependencies]
trust-dns-resolver = "0.19.5"
thiserror = "1.0.20"
byteorder = "1.3.4"
socket2 = "0.3.15"
rand = "0.7.3"
